apiVersion: v1
kind: Service
metadata:
  name: k8s-go-app
spec:
  selector:
    app: k8s-go-app
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  #- name: https
  #  port: 443
  #  targetPort: 8080
